# настройка сборки и сети для каждого сервиса(модуля).

version: '3.8'
services:
  gateway:
    build: ./gateway
    # ports: ["8080:8080"]
    networks: ["app-net"]

  auth:
    build: ./security_service
    # ports: ["8081:8081"]
    networks: ["app-net"]

  data:
    build: ./db_service
    depends_on: 
    - postgres
    # ports: ["8082:8082"]
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=mydb
    networks: 
      - app-net
      - db-net

  game:
    build: ./game_service
    # ports: ["8083:8083"]
    networks: ["app-net"]
    depends_on:
    - auth
    volumes:
      - /opt/blindtyper/static:/var/www/blindtyper/static:rw

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - gateway
    ports: 
      - "80:80"
    volumes:
      - /opt/blindtyper/static:/var/www/blindtyper/static:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks: ["app-net"]
    
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./PostgresInit:/docker-entrypoint-initdb.d
    networks: ["db-net"]

networks:
  app-net:
    driver: bridge
  db-net:
    driver: bridge

volumes:
  pgdata: